import React, { Component } from 'react';
import Slider from 'infinite-react-carousel';

class Carousel extends Component {
  render() {
    const settings =  {
        centerMode: true,
        shift: 1200
    };
    return (
      <div>
        <Slider { ...settings }>
            <div>
              <p>A couple was in the hospital with COVID. Throughout the stay, the nurses teamed up and brought food, bought clothes, and helped the couple get through it. The couple was my family, so we had heard the story. When I heard this, I was more sensitive to people suffering around me. Optimistic stories like this can motivate people to spread even more optimism whether it is for the right reasons or for the wrong reasons. Life is short and the things that make us happy are transient. But the genuine way we impact people around us gives us that happiness and I believe it’s effects last for eternity. So I want to conglomerate all the lovely stories from people to motivate more people to impact more lives. Because that’s the most we can do in this world.
              </p>
            </div>
            <div>
              <p>I want a user to see what good, hopeful stories are around them and be motivated to add more hopeful stories. Seeing the suffering and goodness of others helps break out of our own shell of self-focus. I want them to be able to explore good stories based on location in an interactive US map.
              </p>
            </div>
            <div>
              <p>The landing page is a state map of the US. Each state is clickable. Clicking on a state highlights the state and gives positive news from that state.</p>
            </div>
            <div>
              <p>Color state by amount of good news generated by state</p>
            </div>
            <div>
              <p>Dropdown to select different types of good news (scientific discoveries, children, food).</p>
            </div>
        </Slider>
       </div>
    );
  }
}

export default Carousel;